name: C/C++ CI

on:
  push:

jobs:
  build:
    runs-on: macos-13
    strategy:
      matrix:
        provider: [TFP0]
        # provider: [TFP0, LIBKRW, LIBKERNRW]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare Theos
        uses: und3fined/theos-action@main

      - name: Build package
        run: |
          cp -rf include/* $THEOS/vendor/include/
          rm -f packages/*
          cp control.template control
          USE_TFP0=1 make package FINALPACKAGE=1
        env:
          DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
          LDFLAGS: "-L/usr/local/opt/llvm/lib"
          CPPFLAGS: "-I/usr/local/opt/llvm/include"
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: fouldecrypt-${{matrix.provider}}
          path: ${{ github.workspace }}/packages/*.deb
